Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Common provisioning"

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.hostname = "web1"
    web1.vm.provision "shell", inline: "echo Provisioning for Web only"
    web1.vm.network :private_network, ip: "10.30.1.10"
  end

  config.vm.define "web2" do |web2|
    web2.vm.hostname = "web2"
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.provision "shell", inline: "echo Provisioning for Db only"
    web2.vm.network :private_network, ip: "10.30.1.11"
  end
end